### ISSUE TITLE
please add more info

### ISSUE THREAD

**Issue by numfin** [skearya/sift#4]
could you please describe project architecture in readme? <3 awesome project btw

**Comment by skearya** [comment]
hello and thanks! i added some info in the readme about what libraries i'm using, if you want any more info on the project i can describe more

**Comment by numfin** [comment]
@skearya i'm interested in more like "who talks with who with what data"

**Comment by skearya** [comment]
sure, on every request (hooks.server.ts) authentication info is added to the request and passed down to other handlers (like +server.ts and page load functions)

Routes:
- `/` (homepage): Fetches data from the [anify api's seasonal route](https://docs.anify.tv/routing/seasonal) and also calls the database for the first 6 episodes from a user's watch history 

- `/search`: [Streams](https://kit.svelte.dev/docs/load#streaming-with-promises) response from [anify's search route](https://docs.anify.tv/routing/searching) with the search query url parameter

- `/[animeId]`: Gets [anime info](https://docs.anify.tv/routing/info), [episodes](https://docs.anify.tv/routing/episodes), and [episode covers](https://docs.anify.tv/routing/episode-covers) with the `animeId` route parameter 

- `/[animeId]/[providerId]/[watchId]/[episode]`: Gets [sources](https://docs.anify.tv/routing/sources) for an episode using all of the route parameters, [anime episodes](https://docs.anify.tv/routing/sources), and [anime info](https://docs.anify.tv/routing/info). After the anime info is fetched, that episode gets added to the users watch history

All of this happens on the server and gets server side rendered or client side rendered 

- `/api/history`: This route gets posted to every 10 seconds while watching an episode and saves episode progress for resuming

**Comment by numfin** [comment]
Amazing thank you
